// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
//      Author: shaojin.han
//      
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

interface NetWorkRequestInterface
{
    void Request(string url, Dictionary<string, string> prams, string msgid, string respFuncName, OnRequestRespScript resp);
    void Request(string url, Dictionary<string, string> prams, string msgid, OnRequestResp resp);

    void Request(string url, OnRequestResp resp);
    void Request(string url, string respFuncName, OnRequestRespScript resp);
}


